const virtualDatabase = {
  destinations: [
    { img: "./images/phuquoc.jpeg", title: "Phu Quoc, Viet Nam", place: 2 },
    { img: "./images/hanoi.jpeg", title: "Ha Noi, Viet Nam", place: 2 },
    { img: "./images/thaibinh.jpeg", title: "Thai Binh, Viet Nam", place: 2 },
    { img: "./images/tamdao.jpeg", title: "Tam Dao, Viet Nam", place: 2 },
  ],
  offers: [
    {
      img: "./images/tamdao1.jpeg",
      tour: "Tam Dao",
      cost: 50,
      title: "Khám phá Chân Mây",
      location: "Tam Dao, Vinh Phuc",
      rate: 4.3,
    },
    {
      img: "./images/sapa.jpeg",
      tour: "Sapa",
      cost: 75,
      title: "Chuyến đi thú vị tại Sapa",
      location: "Lao Cai, Viet Nam",
      rate: 4.5,
    },
    {
      img: "./images/catba.jpeg",
      tour: "Cat Ba",
      cost: 50,
      title: "Cẩm nang du lịch Cát Bà",
      location: "Hai Phong, Viet Nam",
      rate: 4.5,
    },
    {
      img: "https://tienhai.thaibinh.gov.vn/upload/80593/fck/files/076153b407910bcd2e49bd92f96ffef4.jpg",
      tour: "Tien Hai",
      cost: 30,
      title: "Khu du lịch sinh thái Tiền Hải",
      location: "Thai Binh, Viet Nam",
      rate: 4,
    },
    {
      img: "https://ik.imagekit.io/tvlk/blog/2023/05/van-hoa-thai-lan-1.jpg?tr=dpr-2,w-675",
      tour: "Thailand",
      cost: 100,
      title: "Xứ sở chùa vàng",
      location: "BangKok, Thailand",
      rate: 5,
    },
    {
      img: "https://vcdn1-dulich.vnecdn.net/2022/04/18/dulichNinhBinhVnExpress-165027-2285-9515-1650278117.jpg?w=0&h=0&q=100&dpr=2&fit=crop&s=EKON9JHNMuFD31A1AvzEYw",
      tour: "Hoa Lu",
      cost: 30,
      title: "Tìm hiểu khu di tích Hoa Lư",
      location: "Ninh Binh, Viet Nam",
      rate: 4,
    },
  ],
  blogs: [
    {
      title: "Vịnh Hạ Long - 10 địa điểm bạn nhất định phải tới",
      author: "Hieu",
      img: "./images/halong.jpeg",
    },
    {
      title: "Vịnh Hạ Long - Đảo Cát Bà",
      author: "Hieu.",
      img: "./images/catba.jpeg",
    },
    {
      title: "Động Phong Nha - Kẻ Bàng",
      author: "Hieu.",
      img: "./images/phongnha.jpeg",
    },
    {
      title: "Hoàng Thành Huế",
      author: "Hieu.",
      img: "./images/hue.jpeg",
    },
    {
      title: "Đảo Phú Quốc",
      author: " Hieu.",
      img: "./images/phuquoc2.jpeg",
    },
  ],
};
